# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

name: Dependabot Analysis
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "cron"
      cronjob: "0 12 * * 5"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
